    export default [
        {
        "id": "1",
        "title": "Beach Resort",
        "image": "resort.jpg",
        "url": "https://react-beach-resort-project-1111.netlify.app",
        "description": "Reactjs, SCSS, Contentful ",
        },
        {
        "id": "2",
        "title": "Github User",
        "image": "/github.jpg",
        "url": "https://github-user-1111.netlify.app",
        "description": "Reactjs, SCSS, Auth0 ",
        },
        {
        "id": "3",
        "title": "Cocktail ",
        "image": "/cocktail.jpg",
        "url": "https://react-hooks-cocktail-project-1111.netlify.app",
        "description": "Reactjs, SCSS ",
        },
        {
        "id": "4",
        "title": "Cube",
        "image": "cube.jpg",
        "url": "https://my-3d-cube-1111.netlify.app",
        "description": "HTML, CSS, Javascript",
        },
        {
        "id": "5",
        "title": "Random Quote Machine",
        "image": "quote.jpg",
        "url": "https://react-random-quote-machine.netlify.app",
        "description": "Reactjs, SCSS",
        },
        {
        "id": "6",
        "title": "City Slide shows",
        "image": "city.jpg",
        "url": "https://my-slideshow-1111.netlify.app",
        "description": "HTML, CSS, Java Script",
        },
        {
        "id": "7",
        "title": "Hamburger menu",
        "image": "hamburger.jpg",
        "url": "https://my-hamburger-menu-1111.netlify.app",
        "description": "HTML, CSS, Java Script",
        },
        {
        "id": "8",
        "title": "Team Profile",
        "image": "profil.jpg",
        "url": "https://my-profile-card-1111.netlify.app",
        "description": "HTML, CSS, Java Script",
        },
        {
        "id": "9",
        "title": "To Do List",
        "image": "todo.jpg",
        "url": "https://react-todo-list-1111.netlify.app",
        "description": "Reactjs",
        },
    ];
    